# Generated by Django 4.2.3 on 2023-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.FloatField(default=0.0),
        ),
    ]
